/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.4-dev at Fri Nov  6 20:10:00 2015. */

#include "MeterReader_pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t MeterReader_Message_fields[5] = {
    PB_ONEOF_FIELD(message,   1, MESSAGE , ONEOF, STATIC  , FIRST, MeterReader_Message, update, update, &MeterReader_CounterUpdate_fields),
    PB_ONEOF_FIELD(message,   2, MESSAGE , ONEOF, STATIC  , FIRST, MeterReader_Message, calibrate, calibrate, &MeterReader_StartCalibration_fields),
    PB_ONEOF_FIELD(message,   3, MESSAGE , ONEOF, STATIC  , FIRST, MeterReader_Message, settings, settings, &MeterReader_Settings_fields),
    PB_ONEOF_FIELD(message,   4, MESSAGE , ONEOF, STATIC  , FIRST, MeterReader_Message, log, log, &MeterReader_LogMessage_fields),
    PB_LAST_FIELD
};

const pb_field_t MeterReader_LogMessage_fields[3] = {
    PB_FIELD(  1, ENUM    , REQUIRED, STATIC  , FIRST, MeterReader_LogMessage, type, type, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, MeterReader_LogMessage, text, type, 0),
    PB_LAST_FIELD
};

const pb_field_t MeterReader_CounterUpdate_fields[4] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, MeterReader_CounterUpdate, meterId, meterId, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, MeterReader_CounterUpdate, seriesId, meterId, 0),
    PB_FIELD(  3, UINT64  , REQUIRED, STATIC  , OTHER, MeterReader_CounterUpdate, currentCounterValue, seriesId, 0),
    PB_LAST_FIELD
};

const pb_field_t MeterReader_StartCalibration_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t MeterReader_Settings_fields[6] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, MeterReader_Settings, meterId, meterId, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, MeterReader_Settings, seriesId, meterId, 0),
    PB_FIELD(  4, ENUM    , REQUIRED, STATIC  , OTHER, MeterReader_Settings, communicationChannel, seriesId, 0),
    PB_FIELD(  8, UINT32  , REPEATED, STATIC  , OTHER, MeterReader_Settings, risingEdgeAmounts, communicationChannel, 0),
    PB_FIELD(  9, UINT32  , REPEATED, STATIC  , OTHER, MeterReader_Settings, fallingEdgeAmounts, risingEdgeAmounts, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(MeterReader_Message, message.update) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_MeterReader_Message_MeterReader_LogMessage_MeterReader_CounterUpdate_MeterReader_StartCalibration_MeterReader_Settings)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(MeterReader_Message, message.update) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_MeterReader_Message_MeterReader_LogMessage_MeterReader_CounterUpdate_MeterReader_StartCalibration_MeterReader_Settings)
#endif


