/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.4-dev at Sat Aug 22 21:37:00 2015. */

#include "CounterUpdate_pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t MeterReader_CounterUpdate_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, MeterReader_CounterUpdate, meterId, meterId, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, MeterReader_CounterUpdate, seriesId, meterId, 0),
    PB_FIELD(  3, UINT64  , REQUIRED, STATIC  , OTHER, MeterReader_CounterUpdate, currentCounterValue, seriesId, 0),
    PB_LAST_FIELD
};


