# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CounterUpdate.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CounterUpdate.proto',
  package='MeterReader',
  serialized_pb='\n\x13\x43ounterUpdate.proto\x12\x0bMeterReader\"O\n\rCounterUpdate\x12\x0f\n\x07meterId\x18\x01 \x02(\x05\x12\x10\n\x08seriesId\x18\x02 \x02(\r\x12\x1b\n\x13\x63urrentCounterValue\x18\x03 \x02(\x04')




_COUNTERUPDATE = _descriptor.Descriptor(
  name='CounterUpdate',
  full_name='MeterReader.CounterUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='meterId', full_name='MeterReader.CounterUpdate.meterId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seriesId', full_name='MeterReader.CounterUpdate.seriesId', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='currentCounterValue', full_name='MeterReader.CounterUpdate.currentCounterValue', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=36,
  serialized_end=115,
)

DESCRIPTOR.message_types_by_name['CounterUpdate'] = _COUNTERUPDATE

class CounterUpdate(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COUNTERUPDATE

  # @@protoc_insertion_point(class_scope:MeterReader.CounterUpdate)


# @@protoc_insertion_point(module_scope)
