// Code generated by protoc-gen-go.
// source: CounterUpdate.proto
// DO NOT EDIT!

/*
Package MeterReader is a generated protocol buffer package.

It is generated from these files:
	CounterUpdate.proto

It has these top-level messages:
	CounterUpdate
*/
package MeterReader

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type CounterUpdate struct {
	MeterId             *int32  `protobuf:"varint,1,req,name=meterId" json:"meterId,omitempty"`
	SeriesId            *uint32 `protobuf:"varint,2,req,name=seriesId" json:"seriesId,omitempty"`
	CurrentCounterValue *uint64 `protobuf:"varint,3,req,name=currentCounterValue" json:"currentCounterValue,omitempty"`
	XXX_unrecognized    []byte  `json:"-"`
}

func (m *CounterUpdate) Reset()         { *m = CounterUpdate{} }
func (m *CounterUpdate) String() string { return proto.CompactTextString(m) }
func (*CounterUpdate) ProtoMessage()    {}

func (m *CounterUpdate) GetMeterId() int32 {
	if m != nil && m.MeterId != nil {
		return *m.MeterId
	}
	return 0
}

func (m *CounterUpdate) GetSeriesId() uint32 {
	if m != nil && m.SeriesId != nil {
		return *m.SeriesId
	}
	return 0
}

func (m *CounterUpdate) GetCurrentCounterValue() uint64 {
	if m != nil && m.CurrentCounterValue != nil {
		return *m.CurrentCounterValue
	}
	return 0
}
